#!/usr/bin/env node
import { createRequire } from "node:module";
import { Command } from "@effect/cli";
import { NodeContext, NodeRuntime } from "@effect/platform-node";
import { Console, Effect, Layer } from "effect";
import { addCommand } from "./cli/add.js";
import { auditCommand } from "./cli/audit.js";
import { cmdCommand } from "./cli/cmd.js";
import { handleComplete } from "./cli/complete.js";
import { delCommand, deleteCommand } from "./cli/delete.js";
import { envCommand } from "./cli/env.js";
import { envFileCommand } from "./cli/env-file.js";
import { getCommand } from "./cli/get.js";
import { listCommand } from "./cli/list.js";
import { loadCommand } from "./cli/load.js";
import { rootCommand } from "./cli/root.js";
import { runCommand } from "./cli/run.js";
import { searchCommand } from "./cli/search.js";
import { shareCommand } from "./cli/share.js";
import { generateCompletions, type ShellType } from "./completions/index.js";
import {
  DatabaseConfigDefault,
  DatabaseConfigFrom,
} from "./services/database-config.js";
import { SecretStore } from "./services/secret-store.js";

const require = createRequire(import.meta.url);
const pkg = require("../package.json") as { version: string };

const command = rootCommand.pipe(
  Command.withSubcommands([
    addCommand,
    getCommand,
    deleteCommand,
    delCommand,
    searchCommand,
    listCommand,
    runCommand,
    envCommand,
    envFileCommand,
    loadCommand,
    cmdCommand,
    auditCommand,
    shareCommand,
  ])
);

const cli = Command.run(command, {
  name: "envsec",
  version: pkg.version,
});

/**
 * Resolve custom database path from --db flag or ENVSEC_DB env var.
 * Pre-parsed from argv since the layer must be built before CLI parsing.
 */
const resolveCustomDbPath = (): string | undefined => {
  const dbIndex = process.argv.indexOf("--db");
  if (dbIndex !== -1 && dbIndex + 1 < process.argv.length) {
    return process.argv[dbIndex + 1];
  }
  const envDb = process.env.ENVSEC_DB;
  if (envDb && envDb.trim() !== "") {
    return envDb.trim();
  }
  return undefined;
};

/**
 * Intercept --completions to emit our custom dynamic completion scripts
 * instead of the static ones generated by @effect/cli.
 */
const interceptCompletions = (): ShellType | null => {
  const idx = process.argv.indexOf("--completions");
  if (idx === -1) {
    return null;
  }
  const shell = process.argv[idx + 1];
  if (shell === "bash" || shell === "zsh" || shell === "fish") {
    return shell;
  }
  // "sh" is an alias for bash in @effect/cli
  if (shell === "sh") {
    return "bash";
  }
  return null;
};

/**
 * Intercept `__complete <type> [arg]` — hidden subcommand used by
 * shell completion scripts to fetch dynamic values (contexts, keys, commands).
 * Handled before CLI parsing so it never appears in --help.
 */
const interceptComplete = (): { type: string; arg?: string } | null => {
  const args = process.argv.slice(2);
  if (args[0] !== "__complete") {
    return null;
  }
  return { type: args[1] ?? "", arg: args[2] };
};

const shell = interceptCompletions();
const complete = interceptComplete();

if (shell) {
  const bin = "envsec";
  Console.log(generateCompletions(shell, bin)).pipe(NodeRuntime.runMain);
} else if (complete) {
  const customDbPath = resolveCustomDbPath();
  const dbLayer = customDbPath
    ? DatabaseConfigFrom(customDbPath)
    : DatabaseConfigDefault;
  const secretStoreLayer = SecretStore.Default.pipe(Layer.provide(dbLayer));

  handleComplete(complete.type, complete.arg).pipe(
    Effect.provide(secretStoreLayer),
    NodeRuntime.runMain
  );
} else {
  const customDbPath = resolveCustomDbPath();
  const dbLayer = customDbPath
    ? DatabaseConfigFrom(customDbPath)
    : DatabaseConfigDefault;

  const secretStoreLayer = SecretStore.Default.pipe(Layer.provide(dbLayer));

  cli(process.argv).pipe(
    Effect.provide(secretStoreLayer),
    Effect.provide(NodeContext.layer),
    NodeRuntime.runMain
  );
}
